/**
 * ---------------------------------------------------------------------------
 * File name: GridElement.java
 * Project name: SudokuWars
 * ---------------------------------------------------------------------------
 * Creator's name and email: Holden Dalton, daltonh@etsu.edu
 * Creator's name and email: Shay Snyder, snyderse2@etsu.edu
 * Creator's name and email: Hannah Taylor, hannahm1@mail.etsu.edu
 *
 * Course:  CSCI 1260-288
 * Creation Date: April 20, 2020
 * ---------------------------------------------------------------------------
 */

package sudoku;

import javax.swing.JButton;

/**
 * create a JButton class that will represent each
 * of the 81 sections of a standard 9x9 Sudoku board
 *
 * <hr>
 * Date created: April 20, 2020
 * Last modified: April 20, 2020
 * <hr>
 * @author Holden Dalton
 * @author Shay Snyder
 * @author Hannah Taylor
 */
public class GameGridElement extends JButton
{
    /**
     * Randomly generated by compiler and debugger
     */
    private static final long serialVersionUID = 453041018513493742L;

    // global variables
    private JButton button;
    private char answer;
    private char value;

    /**
	 * arg constructor for the GridElement class
     *
	 * <hr>
	 * Date created: April 13, 2020
	 */
    public GameGridElement(int index, char answer, char value)
    {

    } // END: GridElement() arg-constructor
} // END: GridElement class