/**
 * ---------------------------------------------------------------------------
 * File name: GridElement.java
 * Project name: SudokuWars
 * ---------------------------------------------------------------------------
 * Creator's name and email: Shay Snyder, snyderse2@etsu.edu
 *							 Holden Dalton, daltonh@etsu.edu
 *							 Hannah Taylor, taylorhm1@mail.etsu.edu
 *
 * Course:  CSCI 1260-288
 * Creation Date: April 20, 2020
 * ---------------------------------------------------------------------------
 */

package sudoku;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * create a JButton class that will represent each
 * of the 81 sections of a standard 9x9 Sudoku board
 *
 * <hr>
 * Date created: April 20, 2020
 * Last modified: April 20, 2020
 * 
 * <hr>
 * @author Shay Snyder
 * @author Holden Dalton 
 * @author Hannah Taylor 
 */
public class GameGridElement extends GamePanelElement
{
    /**
     * Randomly generated by compiler
     */
    private static final long serialVersionUID = 453041018513493742L;

    // global variable
    private JFrame window; // to hold the game's main frame
    private int index; // used to specify the button's location

    /**
	 * arg constructor for the GameGridElement class
     *
	 * <hr>
	 * Date created: April 21, 2020
	 */
    public GameGridElement(Sudoku game, int index, Settings settings, JFrame window)
    {
        // instantiate the super class
        super(game, settings, game.getElementValue(index), window);

        // instantiate the global variables
        this.window = window;
        this.index = index;

        // add the action listener
        this.addActionListener(new ButtonActionListener());
    } // END: GridElement() arg-constructor


    /**
     * listen if the user clicks the button
     *
     * <hr>
     * Date created: April 22, 2020
     * Last modified: April 22, 2020
     * 
     * <hr>
     * @author Shay Snyder
     */
    private class ButtonActionListener implements ActionListener
    {
        /**
	     * arg constructor for the GameGridElement class
         *
	     * <hr>
	     * Date created: April 21, 2020
	     */
        public void actionPerformed(ActionEvent e)
        {
            // submit the location information to the game
            if(!game.setDesiredElement(index))
            {
                // use JOptionPane to inform the user of the unsuccessful selection
                JOptionPane.showMessageDialog(window,
                                              "You cannot select this cell. It is already correct.",
                                              "SudokuWars",
                                              JOptionPane.WARNING_MESSAGE);
            } // END: if selection isn't valid
        } // END: actionPerformedClass
    } // END: ButtonActionListener class
} // END: GridElement class