/**
 * ---------------------------------------------------------------------------
 * File name: GridElement.java
 * Project name: SudokuWars
 * ---------------------------------------------------------------------------
 * Creator's name and email: Shay Snyder, snyderse2@etsu.edu
 *
 * Course:  CSCI 1260-288
 * Creation Date: April 20, 2020
 * ---------------------------------------------------------------------------
 */

package sudoku;

import java.awt.Color;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 * create a JButton class that will represent each
 * of the 81 sections of a standard 9x9 Sudoku board
 *
 * <hr>
 * Date created: April 20, 2020
 * Last modified: April 20, 2020
 * 
 * <hr>
 * @author Shay Snyder
 */
public class GameGridElement extends JButton
{
    /**
     * Randomly generated by linter
     */
    private static final long serialVersionUID = 453041018513493742L;

    // global variable
    private char value;
    private int index;
    private Settings settings;

    /**
	 * arg constructor for the GridElement class
     *
	 * <hr>
	 * Date created: April 13, 2020
	 */
    public GameGridElement(Sudoku game, int index, Settings settings)
    {
        // instantiate the global variables
        this.value = game.getElementValue(index);
        this.index = index;
        this.settings = settings;

        this.setOpaque(true);
        this.setBackground(Color.decode("#282C34"));

        // set the button's icon
        setIcon();
    } // END: GridElement() arg-constructor

    /**
	 * set the image on the button to the button's current value
     *
	 * <hr>
	 * Date created: April 13, 2020
	 */
    private void setIcon()
    {
        this.setIcon(new ImageIcon("icons/" + value + ".png"));
    } // END: setIcon() method
} // END: GridElement class