/**
 * ---------------------------------------------------------------------------
 * File name: GameLowerPanelElement.java
 * Project name: SudokuWars
 * ---------------------------------------------------------------------------
 * Creator's name and email: Shay Snyder, snyderse2@etsu.edu
 *
 * Course:  CSCI 1260-288
 * Creation Date: April 22, 2020
 * ---------------------------------------------------------------------------
 */

package sudoku;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * create a JButton class that will represent each
 * of the 9 sections of numbers the user can
 * choose from when submitting a move
 *
 * <hr>
 * Date created: April 22, 2020
 * Last modified: April 22, 2020
 * 
 * <hr>
 * @author Shay Snyder
 */
public class GameLowerPanelElement extends GamePanelElement
{
    /**
     * randomly generated by compiler
     */
    private static final long serialVersionUID = -8588366620257020431L;
    
    /**
	 * arg constructor for the GridElement class
     *
	 * <hr>
	 * Date created: April 22, 2020
	 */
    public GameLowerPanelElement(Sudoku game, Settings settings, char value, JFrame window)
    {
        // call the super constructor
        super(game, settings, value, window);

        // add the listener
        this.addActionListener(new ButtonActionListener());
    } // END: GameLowerPanelElement() arg constructor

    /**
     * listen if the user clicks the button
     *
     * <hr>
     * Date created: April 22, 2020
     * Last modified: April 22, 2020
     * <hr>
     * @author Shay Snyder
     */
    private class ButtonActionListener implements ActionListener
    {
        /**
	     * listen if the user clicks the button
         *
	     * <hr>
	     * Date created: April 22, 2020
	     */
        public void actionPerformed(ActionEvent e)
        {
            // submit the desired value to the game
            if(game.submitMove(value))
            {
                // Use JOptionPane to display the move's unsuccessful submission
                JOptionPane.showMessageDialog(window,
                                              "Your move was successful!",
                                              "SudokuWars",
                                              JOptionPane.INFORMATION_MESSAGE);
            } // END: move valid
            else
            {
                // Use JOptionPane to display the move's unsuccessful submission
                JOptionPane.showMessageDialog(window,
                                              "Your move was invalid. Please try again.",
                                              "SudokuWars",
                                              JOptionPane.WARNING_MESSAGE);
            } // END: move invalid
        } // END: actionPerformed()
    } // END: ButtonActionListener class
} // END: GameLowerPanelElement class